## ways of creating array in numpy

In [2]:
from numpy import*
x=array([2,4,6,8,10])
print(x)
print(x.dtype)

[ 2  4  6  8 10]
int32


In [3]:
x=array([2,4,6.0,8,10])
print(x)
print(x.dtype)

[ 2.  4.  6.  8. 10.]
float64


In [5]:
x=array([2,4,6,8,10],float)
print(x)
print(x.dtype)


[ 2.  4.  6.  8. 10.]
float64


In [7]:
w=linspace(2,20,5)
print(w)

[ 2.   6.5 11.  15.5 20. ]


In [9]:
w=logspace(1,10,5)
print(w)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [11]:
k=arange(2,20,3)
print(k)

[ 2  5  8 11 14 17]


In [12]:
k=zeros(4)
print(k)

[0. 0. 0. 0.]


In [13]:
k=ones(6)
print(k)

[1. 1. 1. 1. 1. 1.]


In [15]:
k=zeros(5,int)
print(k)

[0 0 0 0 0]


## copying in array

In [17]:
from numpy import*
A1=array([3,5,7,9])
A2=array([2,4,6,8])
A3=A1+A2
print(A3)

[ 5  9 13 17]


In [19]:
print(concatenate([A1,A3]))

[ 3  5  7  9  5  9 13 17]


In [20]:
print(sin(A1))

[ 0.14112001 -0.95892427  0.6569866   0.41211849]


In [21]:
print(log(A1))


[1.09861229 1.60943791 1.94591015 2.19722458]


In [22]:
print(cos(A1))

[-0.9899925   0.28366219  0.75390225 -0.91113026]


In [25]:
print(sum(A1))

24


In [26]:
print(min(A1))

3


In [27]:
print(max(A2))

8


In [30]:
A1=array([4,5,6,7])
A2=A1
print(A1)
print(A2)
print(id(A1))
print(id(A2))

[4 5 6 7]
[4 5 6 7]
1887077458320
1887077458320


## swallow copy

In [32]:
A2=A1.view()
A1[1]=9
print(A1)
print(A2)
print(id(A1))
print(id(A2))

[4 9 6 7]
[4 9 6 7]
1887077458320
1887077650608


## deep copy

In [33]:
A2=A1.copy()
A1[1]=9
print(A1)
print(A2)
print(id(A1))
print(id(A2))

[4 9 6 7]
[4 9 6 7]
1887077458320
1887059797136
