## matrices


In [1]:
from numpy import*
a=array([
    [1,2,3],
    [6,5,4],
    [9,8,7]
])
print(a.dtype)


int32


In [2]:
print(a.shape)

(3, 3)


In [3]:
print(a.ndim)


2


In [5]:
a1=array([
    [1,3,5,7,9,11],
    [0,2,4,6,8,10]
])
a2=a1.flatten()
a3=a2.reshape(3,4)
print(a3)
    

[[ 1  3  5  7]
 [ 9 11  0  2]
 [ 4  6  8 10]]


In [6]:
a4=a2.reshape(2,2,3)
print(a4)

[[[ 1  3  5]
  [ 7  9 11]]

 [[ 0  2  4]
  [ 6  8 10]]]


In [7]:
m=matrix('1,3 ; 5,7; 0,2 ; 4,6')
print(m)

[[1 3]
 [5 7]
 [0 2]
 [4 6]]


In [8]:
print(diagonal(m))

[1 7]


In [9]:
print(m.max())

7


In [10]:
print(m.min())

0


## *kwargs

In [13]:
def student(name,*data):
    print(name)
    print(data)
student('Aishu',20,'II-btech','csm')

Aishu
(20, 'II-btech', 'csm')


In [4]:
def student(name,*data):
    print(name)
    print(data)
student('nam',age=20,city='hyderabad',clg='jbiet',branch='csm')

TypeError: student() got an unexpected keyword argument 'age'

In [6]:
def student(name,**data):
    print(name)
    print(data)
student('swa',age=19,clg='jbiet',rollno=23,branch='csm')

swa
{'age': 19, 'clg': 'jbiet', 'rollno': 23, 'branch': 'csm'}


In [7]:
def student(name,**data):
    print(name)
    for i,j in data.items():
        print(i,j)
student('sravs',age=20,branch='cse',city='warangal',rollno=64)

sravs
age 20
branch cse
city warangal
rollno 64


## global vs local var

In [8]:
x=18
def func():
    x=20
    print(x)
func()
print(x)

20
18


In [9]:
x=20
def func():
   print(x)
func()
print(x)

20
20


In [11]:
x=35
def func():
    global x
    x=20
    print('local',x)
func()
print('global',x)

local 20
global 20


In [19]:
b=30
print(id(b))
def func():
    b=20
    x=globals()['b']
    print(id(x))
    print(b)
    globals()['b']=40
func()
print(b)

140704483886792
140704483886792
20
40


In [1]:
def count(lst):
    even=0
    odd=0
    for i in lst:
        if i%2==0:
            even+=1
        else:
            odd+=1
    return even,odd
lst=[10,11,12,13,14,15,16,17,18]
even,odd=count(lst)
print("even={},odd={}".format(even,odd))

even=5,odd=4


## fibonacci sequence

In [11]:
def fibo(x):
    firstnum=0
    secondnum=1
    print(firstnum)
    print(secondnum)
    for i in range(2,x):
        thirdnum=firstnum+secondnum
        firstnum=secondnum
        secondnum=thirdnum
        print(thirdnum)

In [12]:
fibo(6)

0
1
1
2
3
5


In [7]:
def fibo(n):
    a=0
    b=1
    print(a)
    print(b)
    for i in range(2,n):
        c=a+b
        a=b
        b=c
        print(c)

In [8]:
fibo(6)

0
1
1
2
3
5


In [81]:
def fibo(n):
    a=0
    b=1
    if n==1:
        print(a)
    else:
        print(a)
        print(b)
        for i in range(2,n):
            c=a+b
            a=b
            b=c
            print(c)
            if b>=80:
                break

In [82]:
fibo(1)

0


In [83]:
fibo(20)

0
1
1
2
3
5
8
13
21
34
55
89
